from flask import request, jsonify, Blueprint
from models import User, ParkingRecord, ParkingSpot, ParkingLot
from extensions import db
from flask_jwt_extended import jwt_required
from decorators import admin_required
from sqlalchemy import func

# This Blueprint handles all routes that are exclusive to the admin role.
admin_bp = Blueprint('admin_bp', __name__)

@admin_bp.route('/users', methods=['GET'])
@jwt_required()
@admin_required()
def get_all_users():
    """Returns a list of all registered users in the system."""
    # Check for a search query parameter in the URL.
    search_username = request.args.get('username')
    
    query = User.query
    
    if search_username:
        # If a search query exists, filter the users by username (case-insensitive).
        query = query.filter(User.username.ilike(f'%{search_username}%'))
        
    users = query.all()
    output = []
    for user in users:
        user_data = {
            'id': user.id,
            'username': user.username,
            'role': user.role
        
        }
        output.append(user_data)
    
    return jsonify({'users': output})

@admin_bp.route('/reservations', methods=['GET'])
@jwt_required()
@admin_required()
def get_all_reservations():
    """Returns a complete history of all parking records from all users."""
    reservations = ParkingRecord.query.order_by(ParkingRecord.parking_timestamp.desc()).all()
    output = []
    for record in reservations:
        user = User.query.get(record.user_id)
        spot = ParkingSpot.query.get(record.spot_id)
        lot = ParkingLot.query.get(spot.lot_id)
        record_data = {
            'reservation_id': record.id,
            'username': user.username,
            'lot_name': lot.prime_location_name,
            'spot_number': spot.spot_number,
            'parking_time': record.parking_timestamp.isoformat() if record.parking_timestamp else None,
            'leaving_time': record.leaving_timestamp.isoformat() if record.leaving_timestamp else None,
            'cost': record.parking_cost
        }
        output.append(record_data)
    
    return jsonify({'reservations': output})

@admin_bp.route('/revenue', methods=['GET'])
@jwt_required()
@admin_required()
def get_revenue_summary():
    """Calculates and returns the total revenue generated by each parking lot."""
    # This is an aggregate query that joins multiple tables and sums the costs.
    revenue_data = db.session.query(
        ParkingLot.prime_location_name,
        func.sum(ParkingRecord.parking_cost).label('total_revenue')
    ).join(ParkingSpot, ParkingLot.id == ParkingSpot.lot_id)\
     .join(ParkingRecord, ParkingSpot.id == ParkingRecord.spot_id)\
     .filter(ParkingRecord.parking_cost.isnot(None))\
     .group_by(ParkingLot.prime_location_name)\
     .all()
     
    output = []
    for lot_name, total_revenue in revenue_data:
        output.append({
            'lot_name': lot_name,
            'total_revenue': round(total_revenue, 2) if total_revenue else 0
        })
    return jsonify({'revenue_summary': output})